<?php

declare(strict_types=1);

namespace App\Repositories\Base;

use App\Models\Contact;

/**
 * @generated by Celeris scaffolding. Do not edit directly.
 * Extend this class in `App\Repositories\ContactRepository`.
 */
class ContactRepositoryBase
{
   /** @var array<int, Contact> */
   private array $rows = [];

   public function __construct()
   {
      $this->rows[1] = new Contact(1, 'Ada', 'Lovelace', '+1-555-0100', 'Analytical St', 36);
   }

   /** @return array<int, Contact> */
   public function all(): array
   {
      return array_values($this->rows);
   }

   public function find(int $id): ?Contact
   {
      return $this->rows[$id] ?? null;
   }

   public function save(Contact $contact): Contact
   {
      $this->rows[$contact->id] = $contact;
      return $contact;
   }

   public function delete(int $id): bool
   {
      if (!isset($this->rows[$id])) {
         return false;
      }

      unset($this->rows[$id]);
      return true;
   }
}
