<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api\Base;

use App\Http\DTOs\CreateContactDto;
use App\Http\DTOs\UpdateContactDto;
use App\Services\ContactService;
use Celeris\Framework\Http\Response;
use Celeris\Framework\Routing\Attribute\Route;

/**
 * @generated by Celeris scaffolding. Do not edit directly.
 * Extend this class in `App\Http\Controllers\Api\ContactController`.
 */
class ContactControllerBase
{
   public function __construct(protected ContactService $service) {}

   #[Route(methods: ['GET'], path: '/', summary: 'List contacts')]
   public function index(): array
   {
      return $this->service->list();
   }


   #[Route(methods: ['GET'], path: '/{id}', summary: 'Get contact')]
   public function show(int $id): array
   {
      return $this->service->getOrFail($id)->toArray();
   }


   #[Route(methods: ['POST'], path: '/', summary: 'Create contact')]
   public function create(CreateContactDto $dto): Response
   {
      $contact = $this->service->create($dto);

      return new Response(
         201,
         ['content-type' => 'application/json; charset=utf-8'],
         (string) json_encode(['id' => $contact->id]),
      );
   }


   #[Route(methods: ['PUT'], path: '/{id}', summary: 'Update contact')]
   public function update(int $id, UpdateContactDto $dto): array
   {
      return $this->service->update($id, $dto)->toArray();
   }
   

   #[Route(methods: ['DELETE'], path: '/{id}', summary: 'Delete contact')]
   public function delete(int $id): Response
   {
      $this->service->remove($id);
      return new Response(204);
   }
}
